# Generated by Django 3.2 on 2021-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='discount',
        ),
        migrations.AddField(
            model_name='receiptline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount'),
        ),
        migrations.AddField(
            model_name='receiptlinecount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount'),
        ),
    ]
