# Generated by Django 3.2 on 2021-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_modifieroptions_modifieroption'),
        ('sales', '0002_auto_20210810_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='modifier_options',
            field=models.ManyToManyField(to='products.ModifierOption'),
        ),
    ]
