# Generated by Django 3.2 on 2021-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_receiptline_modifier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='change amount'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='given_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='given amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Cheque'), (3, 'Card'), (4, 'Voucher'), (5, 'Free'), (6, 'Debt'), (7, 'Points'), (100, 'Unknown')], default=0, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Cheque'), (3, 'Card'), (4, 'Voucher'), (5, 'Free'), (6, 'Debt'), (7, 'Points'), (100, 'Unknown')], default=0, verbose_name='payment type'),
        ),
    ]
