# Generated by Django 3.2 on 2021-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210922_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='refund_completed',
            field=models.BooleanField(default=False, verbose_name='refund completed'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='refund_requested',
            field=models.BooleanField(default=False, verbose_name='refund requested'),
        ),
    ]
