# Generated by Django 3.2 on 2021-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210922_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='sold_by_each',
            field=models.BooleanField(default=True, verbose_name='sold_by_each'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='units'),
        ),
    ]
