# Generated by Django 3.2 on 2021-09-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20210922_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='is_variant',
            field=models.BooleanField(default=False, verbose_name='is variant'),
        ),
    ]
