# Generated by Django 3.2 on 2021-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_receiptline_is_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='customer_info',
            field=models.JSONField(default='{}'),
        ),
    ]
