# Generated by Django 3.2 on 2021-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_receipt_customer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='modifier_opitions_info',
            field=models.JSONField(default=dict, verbose_name='modifier opitions info'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='product_info',
            field=models.JSONField(default=dict, verbose_name='product info'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer_info',
            field=models.JSONField(default=dict, verbose_name='customer_info'),
        ),
    ]
