# Generated by Django 3.2 on 2021-09-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_customer_points'),
        ('sales', '0011_auto_20210922_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='parent_Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_product', to='profiles.customer'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='sold_by_each',
            field=models.BooleanField(default=True, verbose_name='sold by each'),
        ),
    ]
