# Generated by Django 3.2 on 2021-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_rename_parent_product_receiptline_parent_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='modifier_opitions_info',
            field=models.JSONField(default=list, verbose_name='modifier opitions info'),
        ),
    ]
