# Generated by Django 3.2 on 2021-09-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_receiptline_modifier_opitions_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptline',
            name='parent_product',
        ),
    ]
