# Generated by Django 3.2 on 2021-09-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_customer_points'),
        ('sales', '0015_remove_receiptline_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_product', to='profiles.customer'),
        ),
    ]
