# Generated by Django 3.2 on 2021-09-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210922_0617'),
        ('sales', '0016_receiptline_parent_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_product', to='products.product'),
        ),
    ]
