# Generated by Django 3.2 on 2021-09-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_receiptline_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='item_couut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='item count'),
        ),
    ]
