# Generated by Django 3.2 on 2021-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_receipt_item_couut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='item_couut',
            field=models.IntegerField(default=0, verbose_name='item count'),
        ),
    ]
