# Generated by Django 3.2 on 2021-09-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_receiptcount_refund_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='refund_requested',
        ),
    ]
