# Generated by Django 3.2 on 2021-09-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_remove_receipt_refund_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Mpesa'), (3, 'Cheque'), (4, 'Card'), (5, 'Voucher'), (6, 'Free'), (0, 'Debt'), (7, 'Points'), (100, 'Unknown')], default=0, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Mpesa'), (3, 'Cheque'), (4, 'Card'), (5, 'Voucher'), (6, 'Free'), (0, 'Debt'), (7, 'Points'), (100, 'Unknown')], default=0, verbose_name='payment type'),
        ),
    ]
