# Generated by Django 3.2 on 2021-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20210924_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='customer_points_update_completed',
            field=models.BooleanField(default=False, verbose_name='customer points update completed'),
        ),
    ]
