# Generated by Django 3.2 on 2021-09-25 04:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_rename_loyaltysettings_loyaltysetting'),
        ('sales', '0025_receipt_customer_points_update_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Card'), (3, 'Points'), (4, 'Debt'), (5, 'Others')], default=0, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Card'), (3, 'Points'), (4, 'Debt'), (5, 'Others')], default=0, verbose_name='payment type'),
        ),
        migrations.CreateModel(
            name='CustomerDebtCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='debt')),
                ('reg_no', models.BigIntegerField(unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.customer')),
                ('receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='debt')),
                ('reg_no', models.BigIntegerField(unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customer')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.receipt')),
            ],
        ),
    ]
