# Generated by Django 3.2 on 2021-09-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_auto_20210925_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdebtcount',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerdebtcount',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='CustomerDebt',
        ),
        migrations.DeleteModel(
            name='CustomerDebtCount',
        ),
    ]
