# Generated by Django 3.2 on 2021-10-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_receipt_created_date_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='created_date_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='created date timestamp'),
        ),
    ]
