# Generated by Django 3.2 on 2021-11-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_alter_receipt_created_date_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='name',
        ),
    ]
