# Generated by Django 3.2 on 2021-11-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_receipt_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='profile',
        ),
    ]
