# Generated by Django 3.2 on 2021-12-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20211008_0548'),
        ('sales', '0035_remove_receipt_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.discount'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.tax'),
        ),
    ]
