# Generated by Django 3.2 on 2021-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_auto_20211204_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost'),
        ),
    ]
