# Generated by Django 3.2 on 2022-01-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_receiptline_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptline',
            name='modifier_opitions_info',
        ),
        migrations.AddField(
            model_name='receiptline',
            name='modifier_options_info',
            field=models.JSONField(default=list, verbose_name='modifier options info'),
        ),
    ]
