# Generated by Django 3.2 on 2022-01-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_storeshift_shift_completed'),
        ('sales', '0038_auto_20220104_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='shfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storeshift'),
        ),
    ]
