# Generated by Django 3.2 on 2022-01-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_receipt_shfit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='shfit',
            new_name='shift',
        ),
    ]
