# Generated by Django 3.2 on 2022-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_rename_shfit_receipt_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='is_debt'),
        ),
    ]
