# Generated by Django 3.2 on 2022-01-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_receipt_is_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='is debt'),
        ),
    ]
