# Generated by Django 3.2 on 2022-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_alter_receipt_is_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='product_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='product info'),
        ),
    ]
