# Generated by Django 3.2 on 2022-01-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_alter_receiptline_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total_cost'),
        ),
    ]
