# Generated by Django 3.2 on 2022-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_receipt_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total cost'),
        ),
    ]
