# Generated by Django 3.2 on 2022-01-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_alter_receipt_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('payment_type', models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Card'), (3, 'Points'), (4, 'Debt'), (5, 'Others')], default=0, verbose_name='payment type')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.receipt')),
            ],
        ),
    ]
