# Generated by Django 3.2 on 2022-01-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_alter_storepaymentmethod_profile'),
        ('sales', '0046_receiptpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptpayment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='payment_method',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.storepaymentmethod'),
            preserve_default=False,
        ),
    ]
