# Generated by Django 3.2 on 2022-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_auto_20220130_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='receiptcount',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'Money transaction'), (1, 'Debt transaction'), (2, 'Loyalty transaction')], default=0, verbose_name='transaction type'),
        ),
        migrations.AddField(
            model_name='receiptcount',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'Money transaction'), (1, 'Debt transaction'), (2, 'Loyalty transaction')], default=0, verbose_name='transaction type'),
        ),
    ]
