# Generated by Django 3.2 on 2022-02-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_auto_20220130_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='loyalty_points_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='loyalty points amount'),
        ),
    ]
