# Generated by Django 3.2 on 2022-02-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0034_storepaymentmethod'),
        ('sales', '0049_receipt_loyalty_points_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'Money transaction'), (1, 'Debt transaction'), (2, 'Loyalty transaction'), (3, 'Multiple transaction')], default=0, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'Money transaction'), (1, 'Debt transaction'), (2, 'Loyalty transaction'), (3, 'Multiple transaction')], default=0, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='receiptpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storepaymentmethod'),
        ),
    ]
