# Generated by Django 3.2 on 2022-02-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
