# Generated by Django 3.2 on 2022-02-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_delete_storepaymentmethod'),
        ('sales', '0054_invoice_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='store',
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
