# Generated by Django 4.0.8 on 2023-08-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0055_auto_20220222_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='refund_completed',
            new_name='is_refund',
        ),
        migrations.RenameField(
            model_name='receiptcount',
            old_name='refund_completed',
            new_name='is_refund',
        ),
    ]
