# Generated by Django 4.0.8 on 2023-08-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_rename_refund_completed_receipt_is_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='refund_for_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='refund for reg no'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='was_refunded',
            field=models.BooleanField(default=False, verbose_name='was refundend'),
        ),
    ]
