# Generated by Django 4.0.8 on 2023-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_receipt_refund_for_reg_no_receipt_was_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='refunded_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='refunded units'),
        ),
    ]
