# Generated by Django 4.0.8 on 2023-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_receiptline_refunded_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='was_refunded',
            field=models.BooleanField(default=False, verbose_name='was refunded'),
        ),
    ]
