# Generated by Django 4.0.8 on 2023-08-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0039_auto_20230720_1435'),
        ('sales', '0059_alter_receipt_was_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.tax'),
        ),
    ]
