# Generated by Django 4.0.8 on 2023-09-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_receiptline_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_increamental_id',
            field=models.IntegerField(default=0, verbose_name='receipt increamental id'),
        ),
    ]
