# Generated by Django 4.0.8 on 2023-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_receipt_receipt_increamental_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcount',
            name='receipt_increamental_id',
            field=models.IntegerField(default=0, verbose_name='receipt increamental id'),
        ),
    ]
