# Generated by Django 4.0.8 on 2023-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_receiptcount_receipt_increamental_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_increamental_id',
        ),
        migrations.RemoveField(
            model_name='receiptcount',
            name='receipt_increamental_id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='increamental_id',
            field=models.IntegerField(default=0, verbose_name='increamental id'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(default='', max_length=30, verbose_name='receipt number'),
        ),
        migrations.AddField(
            model_name='receiptcount',
            name='increamental_id',
            field=models.IntegerField(default=0, verbose_name='increamental id'),
        ),
    ]
