# Generated by Django 4.0.8 on 2023-09-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0063_remove_receipt_receipt_increamental_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='increamental_id',
        ),
        migrations.RemoveField(
            model_name='receiptcount',
            name='increamental_id',
        ),
    ]
