# Generated by Django 4.0.8 on 2023-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0064_remove_receipt_increamental_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='refund_for_receipt_number',
            field=models.CharField(default='', max_length=30, verbose_name='refund for receipt number'),
        ),
    ]
