# Generated by Django 4.0.8 on 2023-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0065_receipt_refund_for_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost total'),
        ),
    ]
