# Generated by Django 4.0.8 on 2023-09-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0066_receiptline_cost_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='gross_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='gross total amount'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount'),
        ),
    ]
