# Generated by Django 3.2.12 on 2023-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0067_receiptline_gross_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='loyverse_store_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='loyverse store id'),
        ),
    ]
