# Generated by Django 3.2.12 on 2023-09-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0068_receipt_loyverse_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='tax_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='tax info'),
        ),
    ]
