# Generated by Django 3.2.12 on 2023-09-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0069_receiptline_tax_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='receipt number'),
        ),
    ]
