# Generated by Django 4.0.8 on 2023-11-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_product_loyverse_variant_id'),
        ('sales', '0070_alter_receipt_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='refund_for_receipt_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='refund for receipt number'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='modifier_options',
            field=models.ManyToManyField(blank=True, null=True, to='products.modifieroption'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='modifier_options_info',
            field=models.JSONField(blank=True, default=list, verbose_name='modifier options info'),
        ),
    ]
