# Generated by Django 4.0.8 on 2023-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0071_alter_receipt_refund_for_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='category_name',
            field=models.CharField(default='', max_length=100, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='product_name',
            field=models.CharField(default='', max_length=100, verbose_name='product_name'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='receipt number'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='refund_for_receipt_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='refund for receipt number'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='tax_name',
            field=models.CharField(default='', max_length=100, verbose_name='tax name'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='user_name',
            field=models.CharField(default='', max_length=100, verbose_name='user name'),
        ),
    ]
