# Generated by Django 4.0.8 on 2023-11-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0072_receiptline_category_name_receiptline_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='store_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='store reg no'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='user_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='user reg no'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='category_name',
            field=models.CharField(default='', max_length=100, verbose_name='category name'),
        ),
    ]
# Generated by Django 4.0.8 on 2023-11-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0072_receiptline_category_name_receiptline_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='store_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='store reg no'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='user_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='user reg no'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='category_name',
            field=models.CharField(default='', max_length=100, verbose_name='category name'),
        ),
    ]
