# Generated by Django 4.0.8 on 2023-11-08 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0075_receipt_receipt_number_for_testing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='sync_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='sync date'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number_for_testing',
            field=models.CharField(default='', max_length=30, verbose_name='receipt number for testing'),
        ),
    ]
