# Generated by Django 4.0.8 on 2023-11-08 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0077_remove_receiptline_sync_date_receipt_sync_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='sync_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='sync date'),
        ),
    ]
