# Generated by Django 4.0.8 on 2023-11-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0078_alter_receipt_sync_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='changed_stock',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='sync_date',
        ),
    ]
