# Generated by Django 4.0.8 on 2023-11-08 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0079_remove_receipt_changed_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='changed_stock',
            field=models.BooleanField(default=True, verbose_name='changed stock'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sync_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='sync date'),
        ),
    ]
