# Generated by Django 4.0.8 on 2023-11-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0080_receipt_changed_stock_receipt_sync_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(default='', max_length=30, verbose_name='receipt number'),
        ),
    ]
