# Generated by Django 4.0.8 on 2023-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0082_alter_customerdebt_debt_alter_customerdebtcount_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebt',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='debt'),
        ),
        migrations.AlterField(
            model_name='customerdebtcount',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='debt'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='tax amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='change amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='given_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='given amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='loyalty_points_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='loyalty points amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='subtotal amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='tax amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='total cost'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='subtotal amount'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='tax amount'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cost total'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='gross_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='gross total amount'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='refunded_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='refunded units'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='receiptlinecount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='receiptlinecount',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='receiptpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='amount'),
        ),
    ]
