# Generated by Django 4.0.8 on 2023-12-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0083_alter_customerdebt_debt_alter_customerdebtcount_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='store_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='store reg no'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='user reg no'),
        ),
    ]
