# Generated by Django 4.2.8 on 2024-01-03 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0085_receipt_sales_recei_user_re_873332_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
    ]
