# Generated by Django 4.2.8 on 2024-01-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0086_alter_receiptline_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='synced_with_tally',
            field=models.BooleanField(default=False, verbose_name='synced with tally'),
        ),
    ]
