# Generated by Django 4.2.8 on 2024-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0087_receiptline_synced_with_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='stock_marked_for_change',
            field=models.BooleanField(default=True, verbose_name='stock marked for change'),
        ),
    ]
