# Generated by Django 4.2.8 on 2024-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0088_receipt_stock_marked_for_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='stock_marked_for_change',
            field=models.BooleanField(default=False, verbose_name='stock marked for change'),
        ),
    ]
