# Generated by Django 4.0.8 on 2024-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0089_alter_receipt_stock_marked_for_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='stock_marked_for_change',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='stock marked for change'),
        ),
    ]
