# Generated by Django 4.2.8 on 2024-02-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0090_alter_receipt_stock_marked_for_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="receipt_number_for_testing",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                verbose_name="receipt number for testing",
            ),
        ),
    ]
