# Generated by Django 4.2.8 on 2024-02-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0091_alter_receipt_receipt_number_for_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='tims_cu_invoice_number',
            field=models.CharField(blank=True, default='', max_length=35, verbose_name='tims cu invoice number'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tims_cu_serial_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='tims cu serial number'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tims_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='tims description'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tims_rel_doc_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=35, verbose_name='tims rel doc number'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tims_success',
            field=models.BooleanField(db_index=True, default=False, verbose_name='tims success'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tims_verification_url',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='tims verification url'),
        ),
    ]
