# Generated by Django 4.2.8 on 2024-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0092_receipt_tims_cu_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='loyverse_store_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='loyverse store id'),
        ),
    ]
