# Generated by Django 4.2.8 on 2024-04-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0094_receipt_show_discount_breakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='shift',
        ),
    ]
