# Generated by Django 3.2 on 2021-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_category_categorycount_discount_discountcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='rate',
        ),
        migrations.AddField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='rate'),
        ),
    ]
