# Generated by Django 3.2 on 2021-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20210801_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_color',
            field=models.IntegerField(choices=[(0, 'Blue'), (1, 'Orange'), (2, 'Green'), (3, 'Pink'), (4, 'Purple'), (5, 'Yellow'), (6, 'Grey'), (7, 'Pitch')], default=0, verbose_name='image color'),
        ),
    ]
