# Generated by Django 3.2 on 2021-08-05 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_category_image_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.RemoveField(
            model_name='categorycount',
            name='store',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='store',
        ),
        migrations.RemoveField(
            model_name='discountcount',
            name='store',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='store',
        ),
        migrations.RemoveField(
            model_name='taxcount',
            name='store',
        ),
    ]
