# Generated by Django 3.2 on 2021-08-09 09:01

import accounts.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20210805_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_color',
        ),
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(default='#474A49', max_length=7, verbose_name='color code'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[accounts.utils.validators.validate_percentage], verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[accounts.utils.validators.validate_percentage], verbose_name='rate'),
        ),
    ]
