# Generated by Django 3.2 on 2021-08-10 04:50

import accounts.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20210809_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color_code',
            field=models.CharField(default='#474A49', max_length=7, validators=[accounts.utils.validators.validate_code], verbose_name='color code'),
        ),
    ]
