# Generated by Django 3.2 on 2021-08-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_category_color_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'taxes'},
        ),
    ]
