# Generated by Django 3.2 on 2021-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_category_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_count',
            field=models.IntegerField(default=0, verbose_name='product count'),
        ),
    ]
