# Generated by Django 3.2 on 2021-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_category_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stores',
            field=models.ManyToManyField(to='stores.Store'),
        ),
        migrations.AddField(
            model_name='tax',
            name='stores',
            field=models.ManyToManyField(to='stores.Store'),
        ),
    ]
