# Generated by Django 3.2 on 2022-01-04 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_alter_usergeneralsetting_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0016_auto_20211008_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='starting_cash')),
                ('cash_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cash_refunds')),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='actual_cash')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cash difference')),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discounts')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxes')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date start')),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date end')),
                ('shift_closed', models.BooleanField(default=False, verbose_name='shift closed')),
                ('reg_no', models.BigIntegerField(default=0, editable=False, unique=True, verbose_name='reg no')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(0, 'Pay in'), (2, 'out')], verbose_name='payment type')),
                ('sale_payment_type', models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Card'), (3, 'Points'), (4, 'Debt'), (5, 'Others')], verbose_name='sale payment type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('reg_no', models.BigIntegerField(default=0, unique=True, verbose_name='reg no')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeshift')),
            ],
        ),
    ]
