# Generated by Django 3.2 on 2022-01-04 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_shiftpayments_storeshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpayments',
            name='comment',
            field=models.CharField(default='', max_length=30, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='shiftpayments',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='actual_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='actual cash'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='cash_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cash refunds'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='starting_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='starting cash'),
        ),
    ]
