# Generated by Django 3.2 on 2022-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_auto_20220104_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftpayments',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='shiftpayments',
            name='shift_payment_type',
            field=models.IntegerField(choices=[(0, 'Pay in'), (2, 'out')], default=0, verbose_name='shift payment type'),
            preserve_default=False,
        ),
    ]
