# Generated by Django 3.2 on 2022-01-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_auto_20220104_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeshift',
            name='all_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='all refunds'),
        ),
        migrations.AddField(
            model_name='storeshift',
            name='cash_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cash payments'),
        ),
        migrations.AddField(
            model_name='storeshift',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='expected cash'),
        ),
    ]
