# Generated by Django 3.2 on 2022-01-05 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_rename_shiftpayments_shiftpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_payment_type', models.IntegerField(choices=[(0, 'Paid in'), (2, 'Paid out')], verbose_name='shift payment type')),
                ('sale_payment_type', models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Card'), (3, 'Points'), (4, 'Debt'), (5, 'Others')], verbose_name='sale payment type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('comment', models.CharField(default='', max_length=30, verbose_name='comment')),
                ('reg_no', models.BigIntegerField(default=0, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeshift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Card'), (3, 'Points'), (4, 'Debt'), (5, 'Others')], verbose_name='payment type')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeshift')),
            ],
        ),
        migrations.DeleteModel(
            name='ShiftPayment',
        ),
    ]
