# Generated by Django 3.2 on 2022-01-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_auto_20220105_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftcash',
            name='sale_payment_type',
        ),
    ]
