# Generated by Django 3.2 on 2022-01-05 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_remove_shiftcash_sale_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeshift',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='storeshift',
            name='date_start',
        ),
        migrations.AddField(
            model_name='storeshift',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='storeshift',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
    ]
