# Generated by Django 3.2 on 2022-01-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_auto_20220105_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeshift',
            name='shift_completed',
            field=models.BooleanField(default=False, verbose_name='shift completed'),
        ),
    ]
