# Generated by Django 3.2 on 2022-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_storeshift_shift_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeshift',
            name='payments_json',
            field=models.JSONField(default=dict, verbose_name='payments_json'),
        ),
    ]
