# Generated by Django 3.2 on 2022-01-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_auto_20220106_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeshift',
            name='profile',
        ),
    ]
