# Generated by Django 3.2 on 2022-01-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_remove_storeshift_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeshift',
            name='cash_debt_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cash debt payments'),
        ),
        migrations.AddField(
            model_name='storeshift',
            name='debt_payments_json',
            field=models.JSONField(default=dict, verbose_name='debt payments json'),
        ),
    ]
