# Generated by Django 3.2 on 2022-01-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_auto_20220113_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeshift',
            name='end_date_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='end date timestamp'),
        ),
        migrations.AddField(
            model_name='storeshift',
            name='local_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='local reg no'),
        ),
        migrations.AddField(
            model_name='storeshift',
            name='start_date_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='start date timestamp'),
        ),
    ]
