# Generated by Django 3.2 on 2022-01-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_remove_shiftcash_shift_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftcash',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='comment'),
        ),
    ]
