# Generated by Django 3.2 on 2022-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0034_storepaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcash',
            name='local_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='local reg no'),
        ),
    ]
