# Generated by Django 3.2 on 2022-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0036_storeshift_all_refunds_during_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeshift',
            name='all_refunds_during_shift',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='all refunds during shift'),
        ),
    ]
