# Generated by Django 4.0.8 on 2023-07-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0037_alter_storeshift_all_refunds_during_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount'),
        ),
    ]
