# Generated by Django 3.2.12 on 2023-07-20 14:35

import accounts.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0038_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[accounts.utils.validators.validate_percentage], verbose_name='value'),
        ),
    ]
