# Generated by Django 4.0.8 on 2023-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0039_auto_20230720_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='loyverse_store_id',
            field=models.UUIDField(db_index=True, default=0, editable=False, verbose_name='loyverse store id'),
            preserve_default=False,
        ),
    ]
