# Generated by Django 3.2.12 on 2023-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0040_store_loyverse_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='loyverse_tax_id',
            field=models.UUIDField(db_index=True, default=0, editable=False, verbose_name='loyverse tax id'),
            preserve_default=False,
        ),
    ]
