# Generated by Django 4.0.8 on 2023-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0041_tax_loyverse_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='loyverse_category_id',
            field=models.UUIDField(db_index=True, default=0, editable=False, verbose_name='loyverse category id'),
            preserve_default=False,
        ),
    ]
