# Generated by Django 4.0.8 on 2023-09-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0042_category_loyverse_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='loyverse_tax_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='loyverse tax id'),
        ),
    ]
