# Generated by Django 4.0.8 on 2023-09-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0043_alter_tax_loyverse_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='loyverse_category_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='loyverse category id'),
        ),
        migrations.AlterField(
            model_name='store',
            name='loyverse_store_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='loyverse store id'),
        ),
    ]
