# Generated by Django 4.0.8 on 2023-09-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0044_alter_category_loyverse_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_increamental_id',
            field=models.IntegerField(default=0, verbose_name='store increamental id'),
        ),
    ]
