# Generated by Django 4.0.8 on 2023-09-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0045_store_store_increamental_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecount',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store'),
        ),
        migrations.AddField(
            model_name='storecount',
            name='store_increamental_id',
            field=models.IntegerField(default=0, verbose_name='store increamental id'),
        ),
    ]
