# Generated by Django 4.0.8 on 2023-09-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0046_storecount_store_storecount_store_increamental_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecount',
            name='store',
        ),
    ]
