# Generated by Django 4.0.8 on 2023-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0047_remove_storecount_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_increamental_id',
        ),
        migrations.RemoveField(
            model_name='storecount',
            name='store_increamental_id',
        ),
        migrations.AddField(
            model_name='store',
            name='increamental_id',
            field=models.IntegerField(default=0, verbose_name='increamental id'),
        ),
        migrations.AddField(
            model_name='storecount',
            name='increamental_id',
            field=models.IntegerField(default=0, verbose_name='increamental id'),
        ),
    ]
