# Generated by Django 4.0.8 on 2023-09-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0048_remove_store_store_increamental_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
