# Generated by Django 4.0.8 on 2023-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0049_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_truck',
            field=models.BooleanField(default=False, verbose_name='is truck'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_warehouse',
            field=models.BooleanField(default=False, verbose_name='is warehouse'),
        ),
    ]
