# Generated by Django 4.0.8 on 2023-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0050_store_is_truck_store_is_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_store',
            field=models.BooleanField(default=False, verbose_name='is store'),
        ),
    ]
