# Generated by Django 4.0.8 on 2023-12-12 10:37

import accounts.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0053_alter_discount_amount_alter_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[accounts.utils.validators.validate_percentage], verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='shiftcash',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='actual_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='actual cash'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='all_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='all refunds'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='all_refunds_during_shift',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='all refunds during shift'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='cash_debt_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cash debt payments'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='cash_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cash difference'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='cash_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cash payments'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='cash_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cash refunds'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='discounts'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='expected cash'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='gross_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='gross sales'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='net_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='net sales'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='starting_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='starting cash'),
        ),
        migrations.AlterField(
            model_name='storeshift',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='taxes'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=30, validators=[accounts.utils.validators.validate_percentage], verbose_name='rate'),
        ),
    ]
