# Generated by Django 4.0.8 on 2023-12-23 16:42
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0054_alter_discount_amount_alter_discount_value_and_more'),
    ]

    operations = [
        
    ]
