# Generated by Django 4.2.8 on 2023-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0055_case_insensitive_collation'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='store',
        #     name='name',
        #     field=models.CharField(db_collation='case_insensitive', max_length=100, verbose_name='name'),
        # ),
    ]
