# Generated by Django 4.0.8 on 2023-12-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0056_alter_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
