# Generated by Django 4.0.8 on 2024-02-26 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0058_store_synced_with_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deleted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='deleted date'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
    ]
