# Generated by Django 4.2.8 on 2024-03-10 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0059_store_deleted_date_store_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="deleted_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1972, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="deleted date",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        ),
    ]
