# Generated by Django 4.2.8 on 2024-03-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0060_alter_store_deleted_date_alter_store_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="till_number",
            field=models.IntegerField(default=0, verbose_name="till number"),
        ),
    ]
