# Generated by Django 4.0.8 on 2024-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0061_store_till_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_date_str',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='created date str'),
        ),
        migrations.AddField(
            model_name='store',
            name='deleted_date_str',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='deleted date str'),
        ),
    ]
