# Generated by Django 4.2.8 on 2024-04-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0095_remove_receipt_shift'),
        ('stores', '0062_store_created_date_str_store_deleted_date_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeshift',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storeshift',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShiftCash',
        ),
        migrations.DeleteModel(
            name='StoreShift',
        ),
    ]
