# Generated by Django 3.2 on 2021-08-01 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_customer_customercount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0004_auto_20210730_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount')),
                ('payment_type', models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Cheque'), (3, 'Card'), (4, 'Voucher'), (5, 'Free'), (6, 'Debt'), (100, 'Unknown')], default=0, verbose_name='payment type')),
                ('payment_completed', models.BooleanField(default=False, verbose_name='payment completed')),
                ('reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.customer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax')),
                ('payment_type', models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Cheque'), (3, 'Card'), (4, 'Voucher'), (5, 'Free'), (6, 'Debt'), (100, 'Unknown')], default=0, verbose_name='payment type')),
                ('payment_completed', models.BooleanField(default=False, verbose_name='payment completed')),
                ('sale_closed', models.BooleanField(default=False, verbose_name='sale closed')),
                ('reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('created_date_timestamp', models.BigIntegerField(default=0, editable=False, verbose_name='created date timestamp')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.customer')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.discount')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price buy')),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price sell')),
                ('reg_no', models.BigIntegerField(unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.category')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.tax')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/no_image.jpg', upload_to=products.models.product_directory_path, verbose_name='image')),
                ('old_image', models.ImageField(default='images/no_image.jpg', upload_to='', verbose_name='old image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price buy')),
                ('price_sell', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price sell')),
                ('stock_units', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stock units')),
                ('barcode', models.CharField(max_length=100, verbose_name='barcode')),
                ('reg_no', models.BigIntegerField(unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.tax')),
            ],
        ),
    ]
