# Generated by Django 3.2 on 2021-08-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_color',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Mpesa'), (2, 'Cheque'), (3, 'Card'), (4, 'Voucher'), (5, 'Free'), (6, 'Debt'), (100, 'Unknown')], default=0, verbose_name='image color'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Blue'), (1, 'Orange'), (2, 'Green'), (3, 'Pink'), (4, 'Purple'), (5, 'Yellow'), (6, 'Grey'), (100, 'Pitch')], default=0, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='receiptcount',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Blue'), (1, 'Orange'), (2, 'Green'), (3, 'Pink'), (4, 'Purple'), (5, 'Yellow'), (6, 'Grey'), (100, 'Pitch')], default=0, verbose_name='payment type'),
        ),
    ]
