# Generated by Django 3.2 on 2021-08-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20210801_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptline',
            old_name='ticket',
            new_name='receipt',
        ),
    ]
