# Generated by Django 3.2 on 2021-08-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_rename_ticket_receiptline_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='sale_closed',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_closed',
            field=models.BooleanField(default=False, verbose_name='receipt closed'),
        ),
    ]
