# Generated by Django 3.2 on 2021-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_auto_20210801_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=False, verbose_name='track stock'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount'),
        ),
    ]
