# Generated by Django 3.2 on 2021-08-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0007_auto_20210802_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_units',
            field=models.IntegerField(default=0, verbose_name='stock units'),
        ),
    ]
