# Generated by Django 3.2 on 2021-08-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_alter_product_stock_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('product_bundle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventories.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.productbundle'),
        ),
    ]
