# Generated by Django 3.2 on 2021-08-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20210805_0400'),
        ('inventories', '0009_auto_20210802_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.RemoveField(
            model_name='productcount',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(to='stores.Store'),
        ),
    ]
