# Generated by Django 3.2 on 2021-08-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20210805_0400'),
        ('inventories', '0011_auto_20210805_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=0, verbose_name='units')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.DeleteModel(
            name='StockCurrent',
        ),
    ]
