# Generated by Django 3.2 on 2021-10-04 08:28

import accounts.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_customer_current_debt'),
        ('inventories', '0014_auto_20210810_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.BigIntegerField(default=0, editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(blank=True, default='', max_length=30, verbose_name='email')),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[accounts.utils.validators.validate_phone_for_models], verbose_name='phone')),
                ('address', models.CharField(blank=True, default='', max_length=50, verbose_name='address')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='city')),
                ('region', models.CharField(blank=True, default='', max_length=50, verbose_name='region')),
                ('country', models.CharField(blank=True, default='', max_length=50, verbose_name='country')),
                ('reg_no', models.BigIntegerField(default=0, editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
