# Generated by Django 3.2 on 2021-10-04 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_category_product_count'),
        ('products', '0032_auto_20210922_0617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventories', '0015_supplier_suppliercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=500, verbose_name='notes')),
                ('reason', models.IntegerField(choices=[(0, 'Receive items'), (1, 'Inventory count'), (2, 'Loss'), (3, 'Damage')], verbose_name='reason')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='quantity')),
                ('reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='add stock')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.stockadjustment')),
            ],
        ),
    ]
