# Generated by Django 3.2 on 2021-10-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210922_0617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0015_alter_category_product_count'),
        ('inventories', '0018_transferorder_transferorderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='expected stock')),
                ('counted_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='counted stock')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='difference')),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='loss')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.stockadjustment')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=500, verbose_name='notes')),
                ('mismatch_found', models.BooleanField(default=False, verbose_name='mismatch found')),
                ('reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
