# Generated by Django 3.2 on 2021-10-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0019_inventorycount_inventorycountline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycountline',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='inventorycountline',
            name='stock_adjustment',
        ),
        migrations.AddField(
            model_name='inventorycountline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost'),
        ),
        migrations.AddField(
            model_name='inventorycountline',
            name='inventory_count',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventorycount'),
            preserve_default=False,
        ),
    ]
