# Generated by Django 3.2 on 2021-10-07 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210922_0617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0015_alter_category_product_count'),
        ('inventories', '0020_auto_20211004_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='expected stock')),
                ('counted_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='counted stock')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='difference')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.inventorycount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=500, verbose_name='notes')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Received'), (2, 'Closed')], verbose_name='status')),
                ('received', models.BooleanField(default=False, verbose_name='Received')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('expected_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='expected date')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
