# Generated by Django 3.2 on 2021-10-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0021_purchaseorder_purchaseorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='postal code'),
        ),
    ]
