# Generated by Django 3.2 on 2021-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0022_supplier_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentline',
            name='product_info',
            field=models.JSONField(default=dict, verbose_name='product info'),
        ),
    ]
