# Generated by Django 3.2 on 2021-10-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0023_stockadjustmentline_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='notes'),
        ),
    ]
