# Generated by Django 3.2 on 2021-10-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0024_alter_stockadjustment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountline',
            name='product_info',
            field=models.JSONField(default=dict, verbose_name='product info'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='product_info',
            field=models.JSONField(default=dict, verbose_name='product info'),
        ),
        migrations.AddField(
            model_name='transferorderline',
            name='product_info',
            field=models.JSONField(default=dict, verbose_name='product info'),
        ),
    ]
