# Generated by Django 3.2 on 2021-10-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0025_auto_20211018_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferorderline',
            name='add_stock',
        ),
        migrations.AddField(
            model_name='transferorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='quantity'),
        ),
    ]
