# Generated by Django 3.2 on 2021-10-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0026_auto_20211018_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferorderline',
            name='cost',
        ),
    ]
