# Generated by Django 3.2 on 2021-10-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0027_remove_transferorderline_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='stores_info',
            field=models.JSONField(default=dict, verbose_name='stores info'),
        ),
    ]
