# Generated by Django 3.2 on 2021-10-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0028_transferorder_stores_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferorder',
            name='stores_info',
        ),
    ]
