# Generated by Django 3.2 on 2021-10-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0029_remove_transferorder_stores_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycountline',
            name='cost',
        ),
        migrations.AddField(
            model_name='inventorycountline',
            name='cost_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost difference'),
        ),
    ]
