# Generated by Django 3.2 on 2021-10-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0032_auto_20211021_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_completed',
            field=models.BooleanField(default=False, editable=False, verbose_name='order completed'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received',
            field=models.BooleanField(default=False, verbose_name='received'),
        ),
    ]
