# Generated by Django 3.2 on 2021-10-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0033_auto_20211021_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_date_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='created date timestamp'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_date_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='expected date timestamp'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Received'), (2, 'Closed')], default=0, verbose_name='status'),
        ),
    ]
