# Generated by Django 3.2 on 2021-10-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0034_auto_20211021_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount'),
        ),
    ]
