# Generated by Django 3.2 on 2021-10-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0036_auto_20211024_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_date_timestamp',
        ),
    ]
