# Generated by Django 3.2 on 2021-10-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0037_remove_purchaseorder_created_date_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='received',
        ),
    ]
