# Generated by Django 3.2 on 2021-11-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0039_stocklevel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='minimum_stock_level',
            field=models.IntegerField(default=0, verbose_name='minimum stock level'),
        ),
    ]
