# Generated by Django 4.0.8 on 2023-06-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0041_stockadjustmentline_expected_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockadjustmentline',
            old_name='expected_stock',
            new_name='counted_stock',
        ),
        migrations.RemoveField(
            model_name='inventorycountline',
            name='expected_stock',
        ),
    ]
