# Generated by Django 4.0.8 on 2023-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0042_rename_expected_stock_stockadjustmentline_counted_stock_and_more'),
    ]

    operations = [
        
    ]
