# Generated by Django 4.0.8 on 2023-07-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0043_inventorycountline_expected_stock'),
        ('inventories', '0043_inventorycountline_expected_stock_and_more'),
    ]

    operations = [
    ]
