# Generated by Django 4.0.8 on 2023-07-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0044_merge_20230703_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='reg_no',
            field=models.BigIntegerField(default=0, editable=False, unique=False, verbose_name='reg no'),
            preserve_default=False,
        ),
    ]
