# Generated by Django 4.0.8 on 2023-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0045_purchaseorderline_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Received'), (2, 'Closed')], default=0, verbose_name='status'),
        ),
    ]
