# Generated by Django 4.0.8 on 2023-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0046_transferorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorderline',
            name='reg_no',
            field=models.BigIntegerField(default=0, editable=False, verbose_name='reg no'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='reg_no',
            field=models.BigIntegerField(editable=False, verbose_name='reg no'),
        ),
    ]
