# Generated by Django 4.0.8 on 2023-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0048_alter_purchaseorderline_reg_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferorder',
            name='reg_no',
            field=models.BigIntegerField(editable=False, unique=True, verbose_name='reg no'),
        ),
    ]
