# Generated by Django 4.0.8 on 2023-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0049_alter_transferorder_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='order_completed',
            field=models.BooleanField(default=False, editable=False, verbose_name='order completed'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='reg_no',
            field=models.BigIntegerField(editable=False, verbose_name='reg no'),
        ),
    ]
