# Generated by Django 4.0.8 on 2023-07-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_product_track_stock'),
        ('stores', '0038_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventories', '0050_transferorder_order_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(0, 'Sale'), (1, 'Refund'), (2, 'Receive'), (3, 'Transfer'), (4, 'Inventory count'), (5, 'Damage'), (6, 'Loss'), (7, 'Production'), (8, 'Item edit')], default=0, verbose_name='status')),
                ('adjustement', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='adjustement')),
                ('stock_after', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stock_after')),
                ('reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
