# Generated by Django 4.0.8 on 2023-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0051_inventoryhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryhistory',
            name='adjustement',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='adjustment'),
        ),
    ]
