# Generated by Django 4.0.8 on 2023-07-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0052_remove_inventoryhistory_adjustement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='change_source_desc',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='change source desc'),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='change_source_reg_no',
            field=models.BigIntegerField(default=0, editable=False, verbose_name='reg no'),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Sale'), (1, 'Refund'), (2, 'Receive'), (3, 'Transfer'), (4, 'Inventory count'), (5, 'Damage'), (6, 'Loss'), (7, 'Production'), (8, 'Item edit')], default=0, verbose_name='reason'),
        ),
    ]
