# Generated by Django 4.0.8 on 2023-07-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0054_auto_20230726_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='change_source_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='change source name'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='order_completed',
            field=models.BooleanField(default=False, verbose_name='order completed'),
        ),
    ]
