# Generated by Django 4.0.8 on 2023-07-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0055_inventoryhistory_change_source_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Closed')], default=0, verbose_name='status'),
        ),
    ]
