# Generated by Django 4.0.8 on 2023-08-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0058_inventorycountline_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='order_completed',
            field=models.BooleanField(default=False, verbose_name='order completed'),
        ),
    ]
