# Generated by Django 4.0.8 on 2023-08-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0060_remove_inventorycount_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountline',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='product cost'),
        ),
    ]
