# Generated by Django 4.0.8 on 2023-09-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0061_inventorycountline_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
    ]
