# Generated by Django 3.2.12 on 2023-09-05 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0062_stocklevel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='completed date'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='completed_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='completed date'),
        ),
    ]
