# Generated by Django 4.0.8 on 2023-09-06 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0063_auto_20230905_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='completed_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='completed date'),
        ),
    ]
