# Generated by Django 4.0.8 on 2023-09-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0067_inventorycount_increamental_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_date_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='created date timestamp'),
        ),
    ]
