# Generated by Django 4.0.8 on 2023-09-27 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0047_remove_productproductionmap_reg_no'),
        ('stores', '0052_remove_store_is_store_store_is_shop'),
        ('inventories', '0068_purchaseorder_created_date_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDisassembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='notes')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Received'), (2, 'Closed')], default=0, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount')),
                ('order_completed', models.BooleanField(default=False, editable=False, verbose_name='order completed')),
                ('increamental_id', models.IntegerField(default=0, verbose_name='increamental id')),
                ('reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('created_date_timestamp', models.BigIntegerField(default=0, verbose_name='created date timestamp')),
                ('expected_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='expected date')),
                ('expected_date_timestamp', models.BigIntegerField(default=0, verbose_name='expected date timestamp')),
                ('completed_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='completed date')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Sale'), (1, 'Refund'), (2, 'Receive'), (3, 'Receive'), (4, 'Transfer'), (5, 'Inventory count'), (6, 'Damage'), (7, 'Loss'), (8, 'Production Assembly'), (9, 'Production Disassembly')], default=0, verbose_name='reason'),
        ),
        migrations.CreateModel(
            name='ProductDisassemblyLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_info', models.JSONField(default=dict, verbose_name='product info')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='quantity')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='purchase cost')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('reg_no', models.BigIntegerField(editable=False, verbose_name='reg no')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_disassembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.productdisassembly')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDisassemblyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.BigIntegerField(default=0, unique=True, verbose_name='reg no')),
                ('increamental_id', models.IntegerField(default=0, verbose_name='increamental id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
