# Generated by Django 4.0.8 on 2023-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0069_productdisassembly_alter_inventoryhistory_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisassembly',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='productdisassembly',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total quantity'),
        ),
    ]
