# Generated by Django 4.0.8 on 2023-09-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0070_remove_productdisassembly_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisassembly',
            name='notes',
        ),
    ]
