# Generated by Django 4.0.8 on 2023-09-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0071_remove_productdisassembly_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisassembly',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='productdisassembly',
            name='created_date_timestamp',
        ),
        migrations.RemoveField(
            model_name='productdisassembly',
            name='expected_date',
        ),
        migrations.RemoveField(
            model_name='productdisassembly',
            name='expected_date_timestamp',
        ),
    ]
