# Generated by Django 4.0.8 on 2023-09-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0072_remove_productdisassembly_completed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisassembly',
            name='order_completed',
        ),
        migrations.RemoveField(
            model_name='productdisassembly',
            name='status',
        ),
    ]
