# Generated by Django 4.0.8 on 2023-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0073_remove_productdisassembly_order_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisassemblyline',
            name='purchase_cost',
        ),
        migrations.AddField(
            model_name='productdisassemblyline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Sale'), (1, 'Refund'), (2, 'Receive'), (3, 'Receive'), (4, 'Transfer'), (5, 'Damage'), (6, 'Loss'), (7, 'Production Assembly'), (8, 'Production Disassembly')], default=0, verbose_name='reason'),
        ),
    ]
