# Generated by Django 3.2.12 on 2023-10-03 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0049_product_is_transformable'),
        ('stores', '0052_remove_store_is_store_store_is_shop'),
        ('inventories', '0075_stocklevel_loyverse_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransformingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product_info', models.JSONField(default=dict, verbose_name='source_product info')),
                ('target_product_info', models.JSONField(default=dict, verbose_name='target_product info')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='quantity')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('reg_no', models.BigIntegerField(editable=False, verbose_name='reg no')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductDisassemblyCount',
            new_name='ProductTransformingCount',
        ),
        migrations.RenameModel(
            old_name='ProductDisassembly',
            new_name='ProductTransforming',
        ),
        migrations.DeleteModel(
            name='ProductDisassemblyLine',
        ),
        migrations.AddField(
            model_name='producttransformingline',
            name='product_transforming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.producttransforming'),
        ),
        migrations.AddField(
            model_name='producttransformingline',
            name='source_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_product', to='products.product'),
        ),
        migrations.AddField(
            model_name='producttransformingline',
            name='target_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_product', to='products.product'),
        ),
    ]
