# Generated by Django 3.2.12 on 2023-10-03 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_product_is_transformable'),
        ('stores', '0052_remove_store_is_store_store_is_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventories', '0076_auto_20231003_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTransforming',
            new_name='ProductTransform',
        ),
        migrations.RenameModel(
            old_name='ProductTransformingCount',
            new_name='ProductTransformCount',
        ),
        migrations.RenameModel(
            old_name='ProductTransformingLine',
            new_name='ProductTransformLine',
        ),
    ]
