# Generated by Django 4.0.8 on 2023-10-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0077_auto_20231003_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttransformline',
            old_name='product_transforming',
            new_name='product_transform',
        ),
    ]
