# Generated by Django 4.0.8 on 2023-10-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0078_rename_product_transforming_producttransformline_product_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransform',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Received'), (2, 'Closed')], default=0, verbose_name='status'),
        ),
    ]
