# Generated by Django 4.0.8 on 2023-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0079_producttransform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransform',
            name='order_completed',
            field=models.BooleanField(default=False, editable=False, verbose_name='order completed'),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Sale'), (1, 'Refund'), (2, 'Receive'), (3, 'Receive'), (4, 'Transfer'), (5, 'Damage'), (6, 'Loss'), (7, 'Repackage')], default=0, verbose_name='reason'),
        ),
    ]
