# Generated by Django 4.0.8 on 2023-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0080_producttransform_order_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransformline',
            name='is_reverse',
            field=models.BooleanField(default=True, verbose_name='is reverse'),
        ),
        migrations.AlterField(
            model_name='producttransformline',
            name='source_product_info',
            field=models.JSONField(default=dict, verbose_name='source product info'),
        ),
        migrations.AlterField(
            model_name='producttransformline',
            name='target_product_info',
            field=models.JSONField(default=dict, verbose_name='target product info'),
        ),
    ]
