# Generated by Django 3.2.12 on 2023-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0081_producttransformline_is_reverse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransformline',
            name='is_reverse',
            field=models.BooleanField(default=False, verbose_name='is reverse'),
        ),
    ]
