# Generated by Django 4.0.8 on 2023-10-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0082_alter_producttransformline_is_reverse'),
        ('inventories', '0082_producttransformline_added_quantity_and_more'),
    ]

    operations = [
    ]
