# Generated by Django 4.0.8 on 2023-10-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0083_merge_20231007_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Sale'), (1, 'Refund'), (2, 'Receive'), (3, 'Receive'), (4, 'Transfer'), (5, 'Damage'), (6, 'Loss'), (7, 'Repackage'), (8, 'Expiry')], default=0, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Receive items'), (1, 'Loss'), (2, 'Damage'), (3, 'Expiry')], verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='loyverse_store_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='loyverse store id'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='loyverse_variant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='loyverse variant id'),
        ),
    ]
