# Generated by Django 4.0.8 on 2023-11-08 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0084_alter_inventoryhistory_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='sync_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='sync date'),
        ),
    ]
