# Generated by Django 4.0.8 on 2023-11-15 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0051_alter_product_loyverse_variant_id'),
        ('stores', '0052_remove_store_is_store_store_is_shop'),
        ('inventories', '0085_inventoryhistory_sync_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='total inventory value')),
                ('total_retail_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='total retail value')),
                ('potential_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='potential profit')),
                ('margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='margin')),
                ('reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryValutionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='units')),
                ('inventory_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='inventory value')),
                ('retail_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='retail value')),
                ('potential_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='potential profit')),
                ('margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='margin')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('store_reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='store reg no')),
                ('product_reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='product reg no')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
                ('inventory_valution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryvalution')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
