# Generated by Django 4.0.8 on 2023-11-15 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0052_remove_store_is_store_store_is_shop'),
        ('products', '0051_alter_product_loyverse_variant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventories', '0086_inventoryvalution_inventoryvalutionline'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValuationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='units')),
                ('inventory_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='inventory value')),
                ('retail_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='retail value')),
                ('potential_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='potential profit')),
                ('margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='margin')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('store_reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='store reg no')),
                ('product_reg_no', models.BigIntegerField(editable=False, unique=True, verbose_name='product reg no')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
        migrations.RenameModel(
            old_name='InventoryValution',
            new_name='InventoryValuation',
        ),
        migrations.DeleteModel(
            name='InventoryValutionLine',
        ),
        migrations.AddField(
            model_name='inventoryvaluationline',
            name='inventory_valution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryvaluation'),
        ),
        migrations.AddField(
            model_name='inventoryvaluationline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='inventoryvaluationline',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventoryvaluationline',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.tax'),
        ),
    ]
