# Generated by Django 4.0.8 on 2023-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0092_alter_inventorycountline_cost_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycountline',
            name='cost_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cost difference'),
        ),
        migrations.AlterField(
            model_name='inventorycountline',
            name='counted_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='counted stock'),
        ),
        migrations.AlterField(
            model_name='inventorycountline',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='difference'),
        ),
        migrations.AlterField(
            model_name='inventorycountline',
            name='expected_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='expected stock'),
        ),
        migrations.AlterField(
            model_name='inventorycountline',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='product cost'),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='adjustment'),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='stock_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='stock_after'),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationline',
            name='inventory_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='inventory value'),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationline',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='margin'),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationline',
            name='potential_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='potential profit'),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationline',
            name='retail_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='retail value'),
        ),
        migrations.AlterField(
            model_name='inventoryvaluationline',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='producttransform',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='total quantity'),
        ),
        migrations.AlterField(
            model_name='producttransformline',
            name='added_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='added quantity'),
        ),
        migrations.AlterField(
            model_name='producttransformline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='producttransformline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='producttransformline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorderadditionalcost',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='purchase cost'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='add_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='add stock'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='counted_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='expected stock'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='remove_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='remove stock'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='units'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='transferorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='quantity'),
        ),
    ]
