# Generated by Django 4.0.8 on 2023-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0094_inventoryvaluationline_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryvaluationline',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='barcode'),
        ),
        migrations.AddField(
            model_name='inventoryvaluationline',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='category name'),
        ),
        migrations.AddField(
            model_name='inventoryvaluationline',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='is sellable'),
        ),
        migrations.AddField(
            model_name='inventoryvaluationline',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='sku'),
        ),
    ]
