# Generated by Django 4.0.8 on 2024-01-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0095_inventoryvaluationline_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='inlude_in_price_calculations',
            field=models.BooleanField(default=True, verbose_name='inlude in price calculations'),
        ),
    ]
