# Generated by Django 4.0.8 on 2024-01-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0096_stocklevel_inlude_in_price_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='line_source_reg_no',
            field=models.BigIntegerField(default=0, editable=False, verbose_name='line source reg no'),
        ),
    ]
