# Generated by Django 4.0.8 on 2024-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0097_inventoryhistory_line_source_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentline',
            name='reg_no',
            field=models.BigIntegerField(default=0, editable=False, verbose_name='reg no'),
        ),
    ]
