# Generated by Django 4.2.8 on 2024-01-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0098_stockadjustmentline_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='line_source_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='line source reg no'),
        ),
    ]
