# Generated by Django 4.0.8 on 2024-01-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0099_alter_inventoryhistory_line_source_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='last_change_source_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='last change source reg no'),
        ),
    ]
