# Generated by Django 4.2.8 on 2024-01-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0102_alter_inventoryhistory_stock_was_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='synced_with_tally',
            field=models.BooleanField(default=False, verbose_name='synced with tally'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='synced_with_tally',
            field=models.BooleanField(default=False, verbose_name='synced with tally'),
        ),
        migrations.AddField(
            model_name='transferorderline',
            name='synced_with_tally',
            field=models.BooleanField(default=False, verbose_name='synced with tally'),
        ),
    ]
