# Generated by Django 4.2.8 on 2024-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0104_inventoryvaluationline_is_recaclulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransform',
            name='auto_repackaged_source_desc',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='auto repackaged source desc'),
        ),
        migrations.AddField(
            model_name='producttransform',
            name='auto_repackaged_source_reg_no',
            field=models.BigIntegerField(default=0, verbose_name='reg no'),
        ),
        migrations.AddField(
            model_name='producttransform',
            name='is_auto_repackaged',
            field=models.BooleanField(default=False, verbose_name='is auto repackaged'),
        ),
    ]
