# Generated by Django 4.2.8 on 2024-03-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0105_producttransform_auto_repackaged_source_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttransform",
            name="auto_repackaged_source_reg_no",
            field=models.BigIntegerField(
                default=0, verbose_name="auto repackaged source reg no"
            ),
        ),
    ]
