# Generated by Django 4.0.8 on 2024-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0106_alter_producttransform_auto_repackaged_source_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='is_auto_created',
            field=models.BooleanField(default=False, verbose_name='is auto created'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='source_description',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='source description'),
        ),
    ]
