# Generated by Django 4.2.8 on 2024-04-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0107_transferorder_is_auto_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferorder",
            name="source_description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="source description",
            ),
        ),
    ]
