LOYVERSE_CUSTOMER_DATA = { 
    'customers': [
        {
            'id': '9ec86d1c-cad9-4886-8d9b-b799d9a71bff', 
            'name': 'Jane Doe', 
            'email': 'jane@gmail.com', 
            'phone_number': '123456768788', 
            'address': 'Nairobi1', 
            'city': None, 
            'region': None, 
            'postal_code': None, 
            'country_code': None, 
            'note': None, 
            'customer_code': '1212jjdoe1234', 
            'first_visit': None, 
            'last_visit': None, 
            'total_visits': 0, 
            'total_spent': 0, 
            'total_points': 0, 
            'permanent_deletion_at': None, 
            'created_at': '2022-07-08T11:14:01.000Z', 
            'updated_at': '2022-07-08T11:14:02.000Z', 
            'deleted_at': None
        },
        {
            'id': '57c22411-8c94-443c-a176-045868621163', 
            'name': 'John Doe', 
            'email': 'john@gmail.com', 
            'phone_number': '223456768788', 
            'address': 'Nakuru1', 
            'city': None, 
            'region': None, 
            'postal_code': None, 
            'country_code': None, 
            'note': None, 
            'customer_code': '2212jjdoe1234', 
            'first_visit': None, 
            'last_visit': None, 
            'total_visits': 0, 
            'total_spent': 0, 
            'total_points': 0, 
            'permanent_deletion_at': None, 
            'created_at': '2022-07-08T11:14:01.000Z', 
            'updated_at': '2022-07-08T11:14:02.000Z', 
            'deleted_at': None
        },
        {
            'id': 'd4a5c42a-f946-4dee-8bb9-fd6cdf1987d0', 
            'name': 'Kevin Gates', 
            'email': 'gates@gmail.com', 
            'phone_number': '1323456768788', 
            'address': 'Mombasa1', 
            'city': None, 
            'region': None, 
            'postal_code': None, 
            'country_code': None, 
            'note': None, 
            'customer_code': '3212jjdoe1234', 
            'first_visit': None, 
            'last_visit': None, 
            'total_visits': 0, 
            'total_spent': 0, 
            'total_points': 0, 
            'permanent_deletion_at': None, 
            'created_at': '2022-07-08T11:14:01.000Z', 
            'updated_at': '2022-07-08T11:14:02.000Z', 
            'deleted_at': None
        }
    ]
}