# Generated by Django 3.2 on 2021-08-10 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_remove_customer_store'),
        ('stores', '0011_alter_category_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/no_image.jpg', upload_to=products.models.product_directory_path, verbose_name='image')),
                ('old_image', models.ImageField(default='images/no_image.jpg', upload_to='', verbose_name='old image')),
                ('image_color', models.IntegerField(choices=[(0, 'Grey'), (1, 'Orange'), (2, 'Green'), (3, 'Pink'), (4, 'Purple'), (5, 'Yellow'), (6, 'Blue'), (7, 'Pitch')], default=0, verbose_name='image color')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price buy')),
                ('price_sell', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price sell')),
                ('barcode', models.CharField(default='', max_length=100, verbose_name='barcode')),
                ('track_stock', models.BooleanField(default=False, verbose_name='track stock')),
                ('reg_no', models.BigIntegerField(unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price buy')),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price sell')),
                ('reg_no', models.BigIntegerField(unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.category')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.tax')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('product_bundle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbundle'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(to='stores.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.tax'),
        ),
    ]
