# Generated by Django 3.2 on 2021-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210810_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='productbundle',
            name='product_bundle',
        ),
        migrations.AddField(
            model_name='product',
            name='show_product',
            field=models.BooleanField(default=True, verbose_name='show product'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
