# Generated by Django 3.2 on 2021-08-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210810_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbundle',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='bundles',
            field=models.ManyToManyField(to='products.ProductBundle'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='product_bundle',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
