# Generated by Django 3.2 on 2021-08-10 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210810_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('reg_no', models.BigIntegerField(unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('reg_no', models.BigIntegerField(unique=True, verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('modifer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.modifier')),
            ],
        ),
    ]
