# Generated by Django 3.2 on 2021-08-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_modifers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modifers',
            new_name='modifiers',
        ),
    ]
