# Generated by Django 3.2 on 2021-08-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210810_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='price',
        ),
        migrations.AddField(
            model_name='modifieroptions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
    ]
