# Generated by Django 3.2 on 2021-08-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_modifer_modifieroptions_modifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModifierOptions',
            new_name='ModifierOption',
        ),
    ]
