# Generated by Django 3.2 on 2021-08-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210810_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_variant_child',
            field=models.BooleanField(default=False, verbose_name='is variant child'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_variant_parent',
            field=models.BooleanField(default=False, verbose_name='is variant parent'),
        ),
    ]
