# Generated by Django 3.2 on 2021-08-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210818_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_each',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by_each',
            field=models.BooleanField(default=True, verbose_name='sold by each'),
        ),
    ]
