# Generated by Django 3.2 on 2021-08-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productvariantoption_productvariantoptionchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_variant_option',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='products.productvariantoption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
