# Generated by Django 3.2 on 2021-08-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210818_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
