# Generated by Django 3.2 on 2021-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productvariantoption_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reg_no',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='reg no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='reg_no',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='reg no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariantoptionchoice',
            name='reg_no',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='reg no'),
            preserve_default=False,
        ),
    ]
