# Generated by Django 3.2 on 2021-08-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210818_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_variant_parent',
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='has variants'),
        ),
    ]
