# Generated by Django 3.2 on 2021-08-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_price_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_sell',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price sell'),
        ),
    ]
