# Generated by Django 3.2 on 2021-08-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_price_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_buy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_sell',
        ),
        migrations.RemoveField(
            model_name='productcount',
            name='price_buy',
        ),
        migrations.RemoveField(
            model_name='productcount',
            name='price_sell',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcount',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcount',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='price'),
            preserve_default=False,
        ),
    ]
