# Generated by Django 3.2 on 2021-08-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210820_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
    ]
