# Generated by Django 3.2 on 2021-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210823_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_count',
            field=models.IntegerField(default=0, verbose_name='variant count'),
        ),
    ]
