# Generated by Django 3.2 on 2021-08-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_is_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_variants',
        ),
    ]
