# Generated by Django 3.2 on 2021-11-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210922_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(default=0, verbose_name='minimum stock level'),
        ),
    ]
