# Generated by Django 3.2 on 2022-05-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_product_minimum_stock_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_image',
        ),
    ]
