# Generated by Django 4.0.8 on 2023-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_product_old_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, verbose_name='track stock'),
        ),
    ]
