# Generated by Django 4.0.8 on 2023-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_product_track_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rate'),
            preserve_default=False,
        ),
    ]
