# Generated by Django 4.0.8 on 2023-09-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_product_loyverse_variant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='loyverse_variant_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='loyverse variant id'),
        ),
    ]
