# Generated by Django 3.2.12 on 2023-09-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_product_cost_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbundle',
            name='product_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
