# Generated by Django 4.0.8 on 2023-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_productproductionmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productions',
            field=models.ManyToManyField(blank=True, to='products.productproductionmap'),
        ),
    ]
