# Generated by Django 4.0.8 on 2023-09-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_remove_productbundle_name_productproductionmap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproductionmap',
            name='reg_no',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='reg no'),
            preserve_default=False,
        ),
    ]
