# Generated by Django 3.2.12 on 2023-09-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_remove_productproductionmap_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loyverse_tax_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='loyverse tax id'),
        ),
    ]
