# Generated by Django 4.0.8 on 2023-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_product_loyverse_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_transformable',
            field=models.BooleanField(default=False, verbose_name='is_transformable'),
        ),
    ]
