# Generated by Django 3.2.12 on 2023-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_product_is_transformable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_count',
            field=models.IntegerField(default=0, verbose_name='production count'),
        ),
    ]
