# Generated by Django 4.0.8 on 2023-12-23 15:54
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_alter_modifieroption_price_alter_product_cost_and_more'),
    ]

    operations = [
        # CreateCollation(
        #     "case_insensitive",
        #     provider="icu",
        #     locale="und-u-ks-level2",
        #     deterministic=False,
        # ),
    ]
