# Generated by Django 4.0.8 on 2023-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_case_insensitive_collation'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='product',
        #     name='name',
        #     field=models.CharField(db_collation='case_insensitive', max_length=100, verbose_name='name'),
        # ),
    ]
