# Generated by Django 4.0.8 on 2024-02-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproductionmap',
            name='is_auto_repackage',
            field=models.BooleanField(default=True, verbose_name='is_auto_repackage'),
        ),
    ]
