# Generated by Django 4.0.8 on 2024-02-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_productproductionmap_is_auto_repackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='average price'),
        ),
        migrations.AlterField(
            model_name='productproductionmap',
            name='is_auto_repackage',
            field=models.BooleanField(default=False, verbose_name='is_auto_repackage'),
        ),
    ]
