# Generated by Django 4.2.8 on 2024-03-10 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0058_product_average_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deleted_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1972, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="deleted date",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        ),
    ]
