# Generated by Django 3.2 on 2021-07-30 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='amount')),
                ('payed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='payed date')),
                ('parent_reg_no', models.BigIntegerField(default=0, verbose_name='parent reg no')),
                ('account_reg_no', models.BigIntegerField(default=0, verbose_name='account reg no')),
                ('account_type', models.CharField(blank=True, max_length=50, verbose_name='account type')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='duration')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='due date')),
                ('last_payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last payment date')),
                ('days_to_go', models.IntegerField(default=0, verbose_name='days to go')),
                ('expired', models.BooleanField(default=True, verbose_name='expired')),
            ],
        ),
    ]
