# Generated by Django 3.2 on 2021-07-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('mylogentries', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='employee_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylogentries.paymentlog'),
        ),
    ]
