# Generated by Django 3.2 on 2021-08-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='employee_profile',
            new_name='employee_profile',
        ),
    ]
