# Generated by Django 4.0.8 on 2023-09-01 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyverseAppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main', editable=False, max_length=10, unique=True, verbose_name='name')),
                ('access_token', models.CharField(default='a827c4447e9d47a3c98', max_length=100, verbose_name='access token')),
                ('refresh_token', models.CharField(default='b827c4447e9d47a3c98', max_length=100, verbose_name='refresh token')),
                ('access_token_expires_in', models.IntegerField(default=0, editable=False, verbose_name='access token expires in')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('receipt_day_minus_today', models.IntegerField(default=0, verbose_name='receipt day minus today')),
            ],
            options={
                'verbose_name_plural': 'loyverse app data',
            },
        ),
    ]
