# Generated by Django 3.2 on 2021-08-03 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210803_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
