# Generated by Django 3.2 on 2021-08-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usergroup_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='ident_name',
            field=models.CharField(default=0, max_length=30, verbose_name='ident name'),
            preserve_default=False,
        ),
    ]
