# Generated by Django 3.2 on 2021-08-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usergroup_ident_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseDevice',
        ),
    ]
