# Generated by Django 3.2 on 2021-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_firebasedevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_system_created',
            field=models.BooleanField(default=True, verbose_name='is system created'),
        ),
    ]
