# Generated by Django 3.2 on 2021-11-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usergroup_is_system_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='is_owner',
        ),
    ]
