# Generated by Django 3.2 on 2021-11-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usergroup_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='is_system_created',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_owner_group',
            field=models.BooleanField(default=True, verbose_name='is owner group'),
        ),
    ]
