# Generated by Django 3.2 on 2021-11-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211111_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='is_owner_group',
            field=models.BooleanField(default=False, verbose_name='is owner group'),
        ),
    ]
