# Generated by Django 3.2 on 2021-11-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usergroup_is_owner_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='ident_name',
            field=models.CharField(max_length=50, verbose_name='ident name'),
        ),
    ]
