# Generated by Django 3.2 on 2021-11-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usergroup_ident_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='reg_no',
            field=models.BigIntegerField(default=0, editable=False, unique=True, verbose_name='reg no'),
        ),
    ]
