# Generated by Django 3.2 on 2021-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usergroup_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='is_owner_group',
            field=models.BooleanField(default=False, editable=False, verbose_name='is owner group'),
        ),
    ]
