# Generated by Django 3.2 on 2021-12-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_usergroup_is_owner_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(200000000, 'admin'), (1, 'Owner'), (2, 'Employee')], verbose_name='user type'),
        ),
    ]
