# Generated by Django 4.0.8 on 2023-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyverse_employee_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='loyverse employee id'),
        ),
    ]
