# Generated by Django 3.2.12 on 2023-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_loyverse_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loyverse_employee_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='loyverse employee id'),
        ),
    ]
