# Generated by Django 3.2.12 on 2023-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_loyverse_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyverse_store_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='loyverse store id'),
        ),
    ]
