# Generated by Django 3.2 on 2021-07-30 09:14

import accounts.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/no_image.jpg', upload_to=profiles.models.profile_directory_path, verbose_name='image')),
                ('old_image', models.ImageField(default='images/no_image.jpg', upload_to='', verbose_name='old image')),
                ('phone', models.BigIntegerField(default=0, unique=True, validators=[accounts.utils.validators.validate_phone_for_models], verbose_name='phone')),
                ('join_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='join date')),
                ('position', models.CharField(max_length=30, verbose_name='position')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('about', models.CharField(max_length=300, verbose_name='about')),
                ('reg_no', models.BigIntegerField(default=0, editable=False, unique=True, verbose_name='reg no')),
                ('unlocked', models.BooleanField(default=True, verbose_name='unlocked')),
            ],
            bases=(profiles.models.CommonProfileMethodsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/no_image.jpg', upload_to=profiles.models.profile_directory_path, verbose_name='image')),
                ('old_image', models.ImageField(default='images/no_image.jpg', upload_to='', verbose_name='old image')),
                ('phone', models.BigIntegerField(default=0, unique=True, validators=[accounts.utils.validators.validate_phone_for_models], verbose_name='phone')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('join_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='join date')),
                ('about', models.CharField(max_length=300, verbose_name='about')),
                ('company', models.CharField(max_length=30, verbose_name='company')),
                ('company_email', models.EmailField(max_length=30, unique=True, verbose_name='company email')),
                ('company_phone', models.BigIntegerField(default=0, unique=True, validators=[accounts.utils.validators.validate_phone_for_models], verbose_name='company phone')),
                ('position', models.CharField(max_length=30, verbose_name='position')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('currency', models.IntegerField(choices=[(0, 'Usd'), (1, 'Ksh')], default=0, verbose_name='currency')),
                ('reg_no', models.BigIntegerField(default=0, editable=False, unique=True, verbose_name='reg no')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(profiles.models.CommonProfileMethodsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProfileCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfileCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('employee_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.employeeprofile')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
