# Generated by Django 3.2 on 2021-08-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_customer_customercount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofilecount',
            old_name='employee_profile',
            new_name='employee_profile',
        ),
    ]
