# Generated by Django 3.2 on 2021-08-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_cashier_profile_employeeprofilecount_employee_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='store',
        ),
    ]
