# Generated by Django 3.2 on 2021-08-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_category_image_color'),
        ('profiles', '0005_remove_employeeprofile_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='stores',
            field=models.ManyToManyField(to='stores.Store'),
        ),
    ]
