# Generated by Django 3.2 on 2021-08-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_employeeprofile_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='store',
        ),
    ]
