# Generated by Django 3.2 on 2021-08-29 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_customer_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='points'),
        ),
    ]
