# Generated by Django 3.2 on 2021-09-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_loyaltysettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoyaltySettings',
            new_name='LoyaltySetting',
        ),
    ]
