# Generated by Django 3.2 on 2021-09-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_customerdebt_customerdebtcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdebtcount',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerdebtcount',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='CustomerDebt',
        ),
        migrations.DeleteModel(
            name='CustomerDebtCount',
        ),
    ]
