# Generated by Django 3.2 on 2021-09-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210925_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='current debt'),
        ),
    ]
