# Generated by Django 3.2 on 2021-11-02 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_customer_current_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltysetting',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='value'),
        ),
        migrations.CreateModel(
            name='ReceiptSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=500, verbose_name='header')),
                ('footer', models.CharField(default='', max_length=500, verbose_name='footer')),
                ('image', models.ImageField(default='images/no_image.jpg', upload_to=profiles.models.receipt_directory_path, verbose_name='image')),
                ('old_image', models.ImageField(default='images/no_image.jpg', upload_to='', verbose_name='old image')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
