# Generated by Django 3.2 on 2021-11-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20211008_0548'),
        ('profiles', '0019_auto_20211102_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsetting',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
            preserve_default=False,
        ),
    ]
