# Generated by Django 3.2 on 2021-11-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_receiptsetting_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsetting',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
