# Generated by Django 3.2 on 2021-11-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_receiptsetting_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsetting',
            name='footer',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='footer'),
        ),
        migrations.AlterField(
            model_name='receiptsetting',
            name='header',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='header'),
        ),
    ]
