# Generated by Django 3.2 on 2021-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20211105_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role_name',
            field=models.CharField(default='', max_length=50, verbose_name='Role name'),
        ),
    ]
