# Generated by Django 3.2 on 2021-11-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_employeeprofile_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role_reg_no',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='reg no'),
        ),
    ]
