# Generated by Django 3.2 on 2021-11-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_employeeprofile_role_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role_reg_no',
            field=models.BigIntegerField(unique=True, verbose_name='reg no'),
        ),
    ]
