# Generated by Django 3.2 on 2021-12-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_alter_employeeprofile_role_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role_name',
            field=models.CharField(default='', max_length=50, verbose_name='role name'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role_reg_no',
            field=models.BigIntegerField(verbose_name='role reg no'),
        ),
    ]
