# Generated by Django 3.2 on 2021-12-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20211204_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(default='', max_length=30, verbose_name='business name'),
        ),
    ]
