# Generated by Django 3.2 on 2021-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_profile_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
    ]
