# Generated by Django 3.2 on 2021-12-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20211231_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='position',
        ),
    ]
