# Generated by Django 3.2 on 2021-12-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_remove_employeeprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_name',
            field=models.CharField(default='', max_length=60, verbose_name='business name'),
        ),
    ]
