# Generated by Django 3.2 on 2022-01-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20211231_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifts', models.BooleanField(default=False, verbose_name='shifts')),
                ('open_tickets', models.BooleanField(default=False, verbose_name='open tickets')),
                ('low_stock_notifications', models.BooleanField(default=True, verbose_name='low stock notifications')),
                ('negative_stock_alerts', models.BooleanField(default=True, verbose_name='negative stock alerts')),
                ('reg_no', models.BigIntegerField(default=0, editable=False, unique=True, verbose_name='reg no')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
