# Generated by Django 3.2 on 2022-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_alter_usergeneralsetting_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeneralsetting',
            name='low_stock_notifications',
        ),
        migrations.RemoveField(
            model_name='usergeneralsetting',
            name='negative_stock_alerts',
        ),
        migrations.RemoveField(
            model_name='usergeneralsetting',
            name='open_tickets',
        ),
        migrations.RemoveField(
            model_name='usergeneralsetting',
            name='shifts',
        ),
        migrations.AddField(
            model_name='usergeneralsetting',
            name='enable_low_stock_notifications',
            field=models.BooleanField(default=True, verbose_name='enable low stock notifications'),
        ),
        migrations.AddField(
            model_name='usergeneralsetting',
            name='enable_negative_stock_alerts',
            field=models.BooleanField(default=True, verbose_name='enable negative stock alerts'),
        ),
        migrations.AddField(
            model_name='usergeneralsetting',
            name='enable_open_tickets',
            field=models.BooleanField(default=False, verbose_name='enable open tickets'),
        ),
        migrations.AddField(
            model_name='usergeneralsetting',
            name='enable_shifts',
            field=models.BooleanField(default=False, verbose_name='enable shifts'),
        ),
    ]
