# Generated by Django 3.2 on 2022-01-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_storepaymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepaymentmethod',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
