# Generated by Django 3.2 on 2022-02-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_remove_storepaymentmethod_profile'),
        ('sales', '0050_auto_20220202_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorePaymentMethod',
        ),
    ]
