# Generated by Django 3.2 on 2022-05-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_delete_storepaymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='old_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_image',
        ),
    ]
