# Generated by Django 4.0.8 on 2023-07-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
        ('profiles', '0042_customer_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='stores',
        ),
        migrations.AddField(
            model_name='customer',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.storecluster'),
        ),
    ]
