# Generated by Django 4.0.8 on 2023-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_remove_customer_stores_customer_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='village_name',
            field=models.EmailField(blank=True, default='', max_length=30, verbose_name='village name'),
        ),
    ]
