# Generated by Django 4.0.8 on 2023-07-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_alter_customer_village_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='address'),
        ),
    ]
