# Generated by Django 3.2.12 on 2023-07-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='village_name',
            field=models.CharField(default='', max_length=30, verbose_name='village name'),
        ),
    ]
