# Generated by Django 3.2.12 on 2023-08-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_storecluster_profile'),
        ('profiles', '0047_auto_20230719_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.storecluster'),
        ),
    ]
