# Generated by Django 3.2.12 on 2023-08-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_storecluster_profile'),
        ('profiles', '0048_employeeprofile_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='cluster',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='clusters',
            field=models.ManyToManyField(to='clusters.StoreCluster'),
        ),
    ]
