# Generated by Django 4.0.8 on 2023-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_auto_20230820_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyverse_customer_id',
            field=models.UUIDField(db_index=True, default=0, editable=False, verbose_name='loyverse customer id'),
            preserve_default=False,
        ),
    ]
