# Generated by Django 4.0.8 on 2023-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.BigIntegerField(default=0, verbose_name='phone'),
        ),
    ]
