# Generated by Django 3.2.12 on 2023-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_alter_employeeprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
