# Generated by Django 3.2.12 on 2023-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_employeeprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=False, verbose_name='email'),
            preserve_default=False,
        ),
    ]
