# Generated by Django 3.2.12 on 2023-09-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_employeeprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='full_name',
        ),
    ]
