# Generated by Django 4.0.8 on 2023-10-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_auto_20230930_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='loyverse_employee_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='loyverse employee id'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='loyverse_store_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='loyverse store id'),
        ),
    ]
