# Generated by Django 4.0.8 on 2023-12-12 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_alter_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, verbose_name='credit limit'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, verbose_name='current debt'),
        ),
        migrations.AlterField(
            model_name='loyaltysetting',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='value'),
        ),
    ]
