# Generated by Django 4.0.8 on 2024-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_alter_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_pin',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='tax pin'),
        ),
    ]
