# Generated by Django 4.2.8 on 2024-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0060_customer_tax_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_api_user',
            field=models.BooleanField(default=True, verbose_name='is api user'),
        ),
    ]
