# Generated by Django 4.2.8 on 2024-04-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0061_employeeprofile_is_api_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="is_api_user",
            field=models.BooleanField(default=False, verbose_name="is api user"),
        ),
    ]
