# Generated by Django 4.0.8 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0037_alter_storeshift_all_refunds_during_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('reg_no', models.BigIntegerField(db_index=True, unique=True, verbose_name='reg no')),
                ('stores', models.ManyToManyField(to='stores.store')),
            ],
        ),
    ]
