# Generated by Django 3.2.12 on 2023-07-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_auto_20230719_1648'),
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecluster',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
