# Generated by Django 3.2 on 2021-07-30 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('payment_method', models.CharField(default='', max_length=50, verbose_name='payment method')),
                ('mpesa_id', models.PositiveIntegerField(default=0, verbose_name='mpesa id')),
                ('payment_type', models.CharField(default='', max_length=50, verbose_name='payment type')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('reg_no', models.BigIntegerField(verbose_name='reg no')),
                ('duration', models.IntegerField(blank=True, default=0, verbose_name='duration')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, verbose_name='email')),
                ('is_logged_in_as_email', models.EmailField(blank=True, max_length=30, verbose_name='is logged in as email')),
                ('is_logged_in_as', models.BooleanField(default=False, verbose_name='is logged in as')),
                ('os', models.CharField(max_length=15, verbose_name='os')),
                ('device_type', models.CharField(max_length=15, verbose_name='device type')),
                ('browser', models.CharField(max_length=15, verbose_name='browser')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip address')),
                ('view_name', models.CharField(max_length=50, verbose_name='view name')),
                ('request_method', models.CharField(max_length=10, verbose_name='request method')),
                ('status_code', models.PositiveIntegerField(default=0, verbose_name='status code')),
                ('is_api', models.BooleanField(default=False, verbose_name='is api')),
                ('location_update', models.BooleanField(default=False, verbose_name='location update')),
                ('map_loaded', models.BooleanField(default=False, verbose_name='map loaded')),
                ('was_throttled', models.BooleanField(default=False, verbose_name='was throttled')),
                ('response_time', models.FloatField(verbose_name='response time')),
                ('reg_no', models.BigIntegerField(verbose_name='reg no')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time')),
                ('change_message', models.TextField(blank=True, verbose_name='change message')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('object_repr', models.CharField(default='', max_length=200, verbose_name='object repr')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('action_type', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Changed'), (3, 'Deleted')], verbose_name='action type')),
                ('owner_email', models.EmailField(blank=True, max_length=254, verbose_name='owner email')),
                ('panel', models.CharField(default='', max_length=6, verbose_name='panel')),
                ('is_hijacked', models.BooleanField(default=False, verbose_name='is hijacked')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user activity log',
                'verbose_name_plural': 'user activity logs',
                'ordering': ('-action_time',),
            },
        ),
        migrations.CreateModel(
            name='MpesaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(default='', max_length=50, verbose_name='transaction type')),
                ('trans_id', models.CharField(max_length=50, unique=True, verbose_name='trans id')),
                ('trans_time', models.BigIntegerField(verbose_name='trans time')),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='trans amount')),
                ('business_shortcode', models.IntegerField(verbose_name='business shortcode')),
                ('bill_ref_number', models.BigIntegerField(verbose_name='bill ref number')),
                ('invoice_number', models.IntegerField(verbose_name='invoice number')),
                ('org_account_balance', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='org account balance')),
                ('third_party_trans_id', models.CharField(default='', max_length=50, verbose_name='third party trans id')),
                ('msisdn', models.BigIntegerField(verbose_name='msisdn')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='first name')),
                ('middle_name', models.CharField(default='', max_length=50, verbose_name='middle name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='last name')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('paymentlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylogentries.paymentlog')),
            ],
        ),
    ]
