# Generated by Django 4.0.8 on 2023-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogentries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttimeseries',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='requesttimeseries',
            name='is_logged_in_as_email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='is logged in as email'),
        ),
        migrations.AlterField(
            model_name='requesttimeseries',
            name='view_name',
            field=models.CharField(max_length=100, verbose_name='view name'),
        ),
    ]
