# Generated by Django 4.0.8 on 2023-12-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogentries', '0003_alter_requesttimeseries_view_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesalog',
            name='trans_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='trans amount'),
        ),
    ]
