# Generated by Django 4.0.8 on 2023-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogentries', '0004_alter_mpesalog_trans_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesalog',
            name='trans_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='trans amount'),
        ),
    ]
