# Generated by Django 3.2 on 2021-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=300, unique=True, verbose_name='name')),
                ('reset_tokens', models.BooleanField(default=False, verbose_name='reset tokens')),
                ('signups', models.BooleanField(default=True, verbose_name='signups')),
                ('maintenance', models.BooleanField(default=True, verbose_name='maintenance')),
                ('allow_contact', models.BooleanField(default=True, verbose_name='allow contact')),
                ('delete_sessions', models.BooleanField(default=False, verbose_name='delete sessions')),
                ('accept_payments', models.BooleanField(default=True, verbose_name='accept payments')),
                ('accept_mpesa', models.BooleanField(default=True, verbose_name='accept mpesa')),
                ('new_employee', models.BooleanField(default=True, verbose_name='new employee')),
                ('new_product', models.BooleanField(default=True, verbose_name='new product')),
                ('new_customer', models.BooleanField(default=True, verbose_name='new customer')),
                ('new_sale', models.BooleanField(default=True, verbose_name='new sale')),
            ],
        ),
    ]
