# Generated by Django 4.2.8 on 2024-01-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysetting',
            name='receipt_change_stock_task_running',
            field=models.BooleanField(default=True, verbose_name='receipt change stock task running'),
        ),
    ]
