# Generated by Django 4.2.8 on 2024-01-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysettings', '0002_mysetting_receipt_change_stock_task_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysetting',
            name='receipt_change_stock_task_running',
            field=models.BooleanField(default=False, verbose_name='receipt change stock task running'),
        ),
    ]
