# Generated by Django 4.0.8 on 2024-01-16 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysettings', '0004_mysetting_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysetting',
            name='created_date',
        ),
        migrations.AddField(
            model_name='mysetting',
            name='stock_task_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='stock task update date'),
        ),
    ]
