# Generated by Django 3.2 on 2022-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0002_rename_firebasedevicee_firebasedevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasedevice',
            name='is_current_active',
            field=models.BooleanField(default=False, verbose_name='is current active'),
        ),
    ]
