# Generated by Django 3.2 on 2022-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0003_firebasedevice_is_current_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasedevice',
            name='is_current_active',
            field=models.BooleanField(default=True, verbose_name='is current active'),
        ),
    ]
